import { createServer } from "node:http";
import { randomUUID } from "node:crypto";

type Asset={id:string;symbol:string;name:string;rank:number;priceUsd:number;marketCapUsd:number;volume24hUsd:number;change24h:number};
const assets:Asset[]=[{id:"bitcoin",symbol:"BTC",name:"Bitcoin",rank:1,priceUsd:65101,marketCapUsd:1.28e12,volume24hUsd:31e9,change24h:1.82},{id:"ethereum",symbol:"ETH",name:"Ethereum",rank:2,priceUsd:3204,marketCapUsd:385e9,volume24hUsd:14e9,change24h:-.6},{id:"solana",symbol:"SOL",name:"Solana",rank:5,priceUsd:145.2,marketCapUsd:68e9,volume24hUsd:3.1e9,change24h:2.4}];
const sessions=new Map<string,{email:string;watchlist:Set<string>}>(); const observedAt=()=>new Date().toISOString();
const meta=(source:string,coverage:string)=>({source,observedAt:observedAt(),coverage,stale:false});
function send(res:any,status:number,body:unknown){res.writeHead(status,{"content-type":"application/json","access-control-allow-origin":"*"});res.end(JSON.stringify(body))}
function body(req:any):Promise<any>{return new Promise(resolve=>{let s="";req.on("data",(x:Buffer)=>s+=x);req.on("end",()=>{try{resolve(JSON.parse(s||"{}"))}catch{resolve({})}})})}
createServer(async(req,res)=>{const url=new URL(req.url??"/","http://localhost");if(req.method==="POST"&&url.pathname==="/api/v1/auth/dev-session"){const b=await body(req);const token=randomUUID();sessions.set(token,{email:b.email??"demo@cryptopanel.local",watchlist:new Set});return send(res,200,{token,expiresAt:new Date(Date.now()+2592e6).toISOString()})}if(url.pathname.startsWith("/api/v1/")&&!url.pathname.startsWith("/api/v1/auth/")){const token=req.headers.authorization?.replace("Bearer ","");const session=token&&sessions.get(token);if(!session)return send(res,401,{error:"Authentication required."});if(url.pathname==="/api/v1/overview")return send(res,200,{data:{globalMarketCapUsd:2.43e12,volume24hUsd:84.2e9,btcDominance:52.7,ethDominance:17.2,movers:assets,marketBreadth:{advancing:68,declining:31}},metadata:meta("CoinGecko Basic","Top 100 assets by market cap; USD")});if(url.pathname==="/api/v1/assets")return send(res,200,{data:assets,metadata:meta("CoinGecko Basic","Top 100 assets by market cap; USD")});if(url.pathname==="/api/v1/watchlist")return send(res,200,{data:assets.filter(a=>session.watchlist.has(a.id)),metadata:meta("CoinGecko Basic","Private account watchlist")});const match=url.pathname.match(/^\/api\/v1\/watchlist\/([^/]+)$/);if(match){if(req.method==="PUT")session.watchlist.add(match[1]);if(req.method==="DELETE")session.watchlist.delete(match[1]);return send(res,204,{})}if(url.pathname.startsWith("/api/v1/analytics/")){const details={derivatives:["Binance public futures API","Binance-supported perpetual pairs only; not market-wide"],chains:["DefiLlama","Chain-level TVL, stablecoin market cap and DEX volume; not token-level facts"],"etf-flows":["Published BTC/ETH ETF-flow table","BTC/ETH daily flows; last successful value retained as stale"]}[url.pathname.split("/").pop()??""];return send(res,200,{data:[],metadata:{source:details?.[0],coverage:details?.[1],observedAt:null,stale:true,unavailable:true}})}}send(res,404,{error:"Not found"})}).listen(Number(process.env.PORT??3000),"0.0.0.0",()=>console.log("Crypto Panel API on :3000"));
